name       : haskell-x509
version    : 1.7.5
release    : 3
source     :
    - https://hackage.haskell.org/package/x509-1.7.5/x509-1.7.5.tar.gz : b1b0fcbb4aa0d749ed2b54710c2ebd6d900cb932108ad14f97640cf4ca60c7c8
license    : BSD-3-Clause
component  : programming.haskell
summary    : X509 reader and writer
description: |
    X509 reader and writer
builddeps  :
    - haskell-asn1-parse-devel
    - haskell-cabal-install
    - haskell-cryptonite-devel
    - haskell-pem-devel
rundeps    :
    - devel:
        - haskell-asn1-parse-devel
        - haskell-cryptonite-devel
        - haskell-pem-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
