name       : haskell-x509
version    : 1.6.5
release    : 1
source     :
    - http://hackage.haskell.org/package/x509-1.6.5/x509-1.6.5.tar.gz : b53894214e23ab2795f2a9f4c885e37b35a223bbc03763b0017ce06dc8394783
license    : BSD-3-Clause
component  : programming.haskell
summary    : X509 reader and writer
description: |
    X509 reader and writer
builddeps  :
    - haskell-asn1-parse
    - haskell-cabal-install
    - haskell-cryptonite
    - haskell-pem
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
