name       : haskell-x509
version    : 1.7.3
release    : 2
source     :
    - https://hackage.haskell.org/package/x509-1.7.3/x509-1.7.3.tar.gz : 41740f949bb773dc721d342a85587a512658c81ee8cd38f102473b315e127356
license    : BSD-3-Clause
component  : programming.haskell
summary    : X509 reader and writer
description: |
    X509 reader and writer
builddeps  :
    - haskell-asn1-parse
    - haskell-cabal-install
    - haskell-cryptonite
    - haskell-mtl
    - haskell-pem
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
